remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Visual Neural Decoding
description: Neural Decoding and Stimulus Reconstruction Using Neuroimaging and Artificial Intelligence