#!/usr/bin/env python3
"""
BibTeX Cleaner - Standardize IEEE BibTeX to Scopus-like format
Usage: python bibtex_cleaner.py input.bib output.bib
"""

import re
import sys

def clean_bibtex_entry(entry):
    """Clean and standardize a single BibTeX entry"""
    
    # Remove @ARTICLE and replace with @article (lowercase)
    entry = re.sub(r'@ARTICLE\{', '@article{', entry, flags=re.IGNORECASE)
    entry = re.sub(r'@INPROCEEDINGS\{', '@inproceedings{', entry, flags=re.IGNORECASE)
    
    # Standardize field names to lowercase
    fields_to_lowercase = [
        'author', 'title', 'journal', 'booktitle', 'year', 'volume', 
        'number', 'pages', 'doi', 'url', 'keywords', 'abstract',
        'publisher', 'address', 'note', 'issn', 'month'
    ]
    
    for field in fields_to_lowercase:
        # Match field names at start of line with any case
        entry = re.sub(
            rf'(\s+){field}\s*=',
            rf'\1{field.lower()} =',
            entry,
            flags=re.IGNORECASE
        )
    
    # Remove non-standard fields
    fields_to_remove = [
        'author_keywords', 'publication_stage', 'source', 'note',
        'type', 'organization', 'copyright'
    ]
    
    for field in fields_to_remove:
        entry = re.sub(
            rf'\s+{field}\s*=\s*{{[^}}]*}},?\n',
            '',
            entry,
            flags=re.IGNORECASE
        )
    
    # Clean up keywords - remove brackets if nested
    entry = re.sub(
        r'keywords\s*=\s*\{([^{}]+)\}',
        lambda m: f'keywords = {{{m.group(1).strip()}}}',
        entry
    )
    
    # Standardize pages format: {1-4} or {1267-1283}
    entry = re.sub(
        r'pages\s*=\s*\{(\d+)-(\d+)\}',
        r'pages = {\1--\2}',
        entry
    )
    
    # Standardize DOI format
    entry = re.sub(
        r'doi\s*=\s*\{([^}]+)\}',
        lambda m: f'doi = {{{m.group(1).strip()}}}',
        entry
    )
    
    # Remove trailing commas before closing brace
    entry = re.sub(r',(\s*)\}', r'\1}', entry)
    
    # Ensure proper spacing
    entry = re.sub(r'=\s*\{', ' = {', entry)
    
    return entry

def clean_bibtex_file(input_file, output_file):
    """Process entire BibTeX file"""
    
    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            content = f.read()
    except FileNotFoundError:
        print(f"Error: File '{input_file}' not found")
        sys.exit(1)
    
    # Split into individual entries
    entries = re.split(r'(@(?:article|inproceedings|book|misc)\{)', content, flags=re.IGNORECASE)
    
    cleaned_entries = []
    
    # Process entries (entries list has pattern: ['', '@article{', 'content', '@inproceedings{', 'content', ...])
    for i in range(1, len(entries), 2):
        if i + 1 < len(entries):
            entry_type = entries[i]
            entry_content = entries[i + 1]
            full_entry = entry_type + entry_content
            
            cleaned_entry = clean_bibtex_entry(full_entry)
            cleaned_entries.append(cleaned_entry)
    
    # Write cleaned content
    with open(output_file, 'w', encoding='utf-8') as f:
        # Add header comment
        f.write("% BibTeX file cleaned and standardized\n")
        f.write("% Generated by BibTeX Cleaner\n\n")
        
        for entry in cleaned_entries:
            f.write(entry)
            f.write('\n\n')
    
    print(f"✓ Successfully cleaned {len(cleaned_entries)} entries")
    print(f"✓ Output written to: {output_file}")

def main():
    if len(sys.argv) != 3:
        print("Usage: python bibtex_cleaner.py input.bib output.bib")
        print("\nExample:")
        print("  python bibtex_cleaner.py ieee.bib ieee_cleaned.bib")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    
    print(f"Cleaning BibTeX file: {input_file}")
    clean_bibtex_file(input_file, output_file)

if __name__ == "__main__":
    main()